"use client"

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
          <div className="flex flex-col w-full">
            <Header isOpen={isOpen} toggleSidebar={toggleSidebar} />
            <div className="flex-1 p-6 rounded-sm">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
